const LANGUAGES = [
    {'en': [{id: 'Backquote', key: '§', shiftKey: '±'},
        {id: 'Digit1', key: '1', shiftKey: "!"},
        {id: 'Digit2', key: '2', shiftKey: "@"},
        {id: 'Digit3', key: '3', shiftKey: "#"},
        {id: 'Digit4', key: '4', shiftKey: "$"},
        {id: 'Digit5', key: '5', shiftKey: "%"},
        {id: 'Digit6', key: '6', shiftKey: "^"},
        {id: 'Digit7', key: '7', shiftKey: "&"},
        {id: 'Digit8', key: '8', shiftKey: "*"},
        {id: 'Digit9', key: '9', shiftKey: "("},
        {id: 'Digit0', key: '0', shiftKey: ")"},
        {id: 'Minus', key: '-', shiftKey: "_"},
        {id: 'Equal', key: '=', shiftKey: "+"},
        {id: 'Backspace', key: 'Backspace', shiftKey: 'Backspace'},
        {id: 'Tab', key: 'Tab', shiftKey: 'Tab'},
        {id: 'KeyQ', key: 'q', shiftKey: 'Q'},
        {id: 'KeyW', key: 'w', shiftKey: 'W'},
        {id: 'KeyE', key: 'e', shiftKey: 'E'},
        {id: 'KeyR', key: 'r', shiftKey: 'R'},
        {id: 'KeyT', key: 't', shiftKey: 'T'},
        {id: 'KeyY', key: 'y', shiftKey: 'Y'},
        {id: 'KeyU', key: 'u', shiftKey: 'U'},
        {id: 'KeyI', key: 'i', shiftKey: 'I'},
        {id: 'KeyO', key: 'o', shiftKey: 'O'},
        {id: 'KeyP', key: 'p', shiftKey: 'P'},
        {id: 'BracketLeft', key: '[', shiftKey: '{'},
        {id: 'BracketRight', key: ']', shiftKey: '}'},
        {id: 'Enter', key: 'Enter', shiftKey: 'Enter'},
        {id: 'CapsLock', key: 'CapsLock', shiftKey: 'CapsLock'},
        {id: 'KeyA', key: 'a', shiftKey: 'A'},
        {id: 'KeyS', key: 's', shiftKey: 'S'},
        {id: 'KeyD', key: 'd', shiftKey: 'D'},
        {id: 'KeyF', key: 'f', shiftKey: 'F'},
        {id: 'KeyG', key: 'g', shiftKey: 'G'},
        {id: 'KeyH', key: 'h', shiftKey: 'H'},
        {id: 'KeyJ', key: 'j', shiftKey: 'J'},
        {id: 'KeyK', key: 'k', shiftKey: 'K'},
        {id: 'KeyL', key: 'l', shiftKey: 'L'},
        {id: 'Semicolon', key: ';', shiftKey: ':'},
        {id: 'Quote', key: '\'', shiftKey: '\"'},
        {id: 'Backslash', key: '\\', shiftKey: '|'},
        {id: 'Enter', key: '', shiftKey: null},
        {id: 'ShiftLeft', key: 'Shift', shiftKey: 'Shift'},
        {id: 'IntlBackslash', key: '`', shiftKey: '~'},
        {id: 'KeyZ', key: 'z', shiftKey: 'Z'},
        {id: 'KeyX', key: 'x', shiftKey: 'X'},
        {id: 'KeyC', key: 'c', shiftKey: 'C'},
        {id: 'KeyV', key: 'v', shiftKey: 'V'},
        {id: 'KeyB', key: 'b', shiftKey: 'B'},
        {id: 'KeyN', key: 'n', shiftKey: 'N'},
        {id: 'KeyM', key: 'm', shiftKey: 'M'},
        {id: 'Comma', key: ',', shiftKey: '<'},
        {id: 'Period', key: '.', shiftKey: '>'},
        {id: 'Slash', key: '/', shiftKey: '?'},
        {id: 'ShiftRight', key: 'Shift ', shiftKey: 'Shift'},
        {id: 'fn', key: 'fn', width: '60px', shiftKey: 'fn'},
        {id: 'ControlLeft', key: 'ctrl', shiftKey: 'ctrl'},
        {id: 'AltLeft', key: 'alt', shiftKey: 'alt'},
        {id: 'MetaLeft', key: 'cmd', shiftKey: 'cmd'},
        {id: 'Space', key: ' ', shiftKey: ' '},
        {id: 'MetaRight', key: 'cmd ', shiftKey: 'cmd'},
        {id: 'AltRight', key: 'alt ', shiftKey: 'alt'}]
    },
    {'ru': [{id: 'Backquote', key: '>', shiftKey: '<'},
        {id: 'Digit1', key: '1', shiftKey: "!"},
        {id: 'Digit2', key: '2', shiftKey: "\""},
        {id: 'Digit3', key: '3', shiftKey: "№"},
        {id: 'Digit4', key: '4', shiftKey: "%"},
        {id: 'Digit5', key: '5', shiftKey: ":"},
        {id: 'Digit6', key: '6', shiftKey: ","},
        {id: 'Digit7', key: '7', shiftKey: "."},
        {id: 'Digit8', key: '8', shiftKey: ";"},
        {id: 'Digit9', key: '9', shiftKey: "("},
        {id: 'Digit0', key: '0', shiftKey: ")"},
        {id: 'Minus', key: '-', shiftKey: "_"},
        {id: 'Equal', key: '=', shiftKey: "+"},
        {id: 'Backspace', key: 'Backspace', shiftKey: 'Backspace'},
        {id: 'Tab', key: 'Tab', shiftKey: 'Tab'},
        {id: 'KeyQ', key: 'й', shiftKey: 'Й'},
        {id: 'KeyW', key: 'ц', shiftKey: 'Ц'},
        {id: 'KeyE', key: 'у', shiftKey: 'У'},
        {id: 'KeyR', key: 'к', shiftKey: 'К'},
        {id: 'KeyT', key: 'е', shiftKey: 'Е'},
        {id: 'KeyY', key: 'н', shiftKey: 'Н'},
        {id: 'KeyU', key: 'г', shiftKey: 'Г'},
        {id: 'KeyI', key: 'ш', shiftKey: 'Ш'},
        {id: 'KeyO', key: 'щ', shiftKey: 'Щ'},
        {id: 'KeyP', key: 'з', shiftKey: 'З'},
        {id: 'BracketLeft', key: 'х', shiftKey: 'Х'},
        {id: 'BracketRight', key: 'ъ', shiftKey: 'Ъ'},
        {id: 'Enter', key: 'Enter', shiftKey: 'Enter'},
        {id: 'CapsLock', key: 'CapsLock', shiftKey: 'CapsLock'},
        {id: 'KeyA', key: 'ф', shiftKey: 'Ф'},
        {id: 'KeyS', key: 'ы', shiftKey: 'Ы'},
        {id: 'KeyD', key: 'в', shiftKey: 'В'},
        {id: 'KeyF', key: 'а', shiftKey: 'А'},
        {id: 'KeyG', key: 'п', shiftKey: 'П'},
        {id: 'KeyH', key: 'р', shiftKey: 'Р'},
        {id: 'KeyJ', key: 'о', shiftKey: 'О'},
        {id: 'KeyK', key: 'л', shiftKey: 'Л'},
        {id: 'KeyL', key: 'д', shiftKey: 'Д'},
        {id: 'Semicolon', key: 'ж', shiftKey: 'Ж'},
        {id: 'Quote', key: 'э', shiftKey: 'Э'},
        {id: 'Backslash', key: 'ё', shiftKey: 'Ё'},
        {id: 'Enter', key: '', shiftKey: null},
        {id: 'ShiftLeft', key: 'Shift', shiftKey: 'Shift'},
        {id: 'IntlBackslash', key: ']', shiftKey: '['},
        {id: 'KeyZ', key: 'я', shiftKey: 'Я'},
        {id: 'KeyX', key: 'ч', shiftKey: 'Ч'},
        {id: 'KeyC', key: 'с', shiftKey: 'С'},
        {id: 'KeyV', key: 'м', shiftKey: 'М'},
        {id: 'KeyB', key: 'и', shiftKey: 'И'},
        {id: 'KeyN', key: 'т', shiftKey: 'Т'},
        {id: 'KeyM', key: 'ь', shiftKey: 'Ь'},
        {id: 'Comma', key: 'б', shiftKey: 'Б'},
        {id: 'Period', key: 'ю', shiftKey: 'Ю'},
        {id: 'Slash', key: '/', shiftKey: '?'},
        {id: 'ShiftRight', key: 'Shift ', shiftKey: 'Shift'},
        {id: 'fn', key: 'fn', width: '60px', shiftKey: 'fn'},
        {id: 'ControlLeft', key: 'ctrl', shiftKey: 'ctrl'},
        {id: 'AltLeft', key: 'alt', shiftKey: 'alt'},
        {id: 'MetaLeft', key: 'cmd', shiftKey: 'cmd'},
        {id: 'Space', key: ' ', shiftKey: ' '},
        {id: 'MetaRight', key: 'cmd ', shiftKey: 'cmd'},
        {id: 'AltRight', key: 'alt ', shiftKey: 'alt'}]
    }
]


export { LANGUAGES };


// const KEYS = [
//     {id: 0, key: '§', width: '60px', shiftKey: "±", code: 'Backquote'},
//     {id: 1, key: '1', width: '60px', shiftKey: "!", code: 'Digit1'},
//     {id: 2, key: '2', width: '60px', shiftKey: "@", code: 'Digit2'},
//     {id: 3, key: '3', width: '60px', shiftKey: "#", code: 'Digit3'},
//     {id: 4, key: '4', width: '60px', shiftKey: "$", code: 'Digit4'},
//     {id: 5, key: '5', width: '60px', shiftKey: "%", code: 'Digit5'},
//     {id: 6, key: '6', width: '60px', shiftKey: "^", code: 'Digit6'},
//     {id: 7, key: '7', width: '60px', shiftKey: "&", code: 'Digit7'},
//     {id: 8, key: '8', width: '60px', shiftKey: "*", code: 'Digit8'},
//     {id: 9, key: '9', width: '60px', shiftKey: "(", code: 'Digit9'},
//     {id: 10, key: '0', width: '60px', shiftKey: ")", code: 'Digit0'},
//     {id: 11, key: '-', width: '60px', shiftKey: "_", code: 'Minus'},
//     {id: 12, key: '=', width: '60px', shiftKey: "+", code: 'Equal'},
//     {id: 13, key: '←', width: '90px', shiftKey: null, code: 'Backspace'},
//     {id: 13, key: 'Tab', width: '90px', shiftKey: null, code: "Tab"},
//     {id: 13, key: 'q', width: '60px', shiftKey: 'Q', code: 'KeyQ'},
//     {id: 13, key: 'w', width: '60px', shiftKey: 'W', code: 'KeyW'},
//     {id: 13, key: 'e', width: '60px', shiftKey: 'E', code: 'KeyE'},
//     {id: 13, key: 'r', width: '60px', shiftKey: 'R', code: 'KeyR'},
//     {id: 13, key: 't', width: '60px', shiftKey: 'T', code: 'KeyT'},
//     {id: 13, key: 'y', width: '60px', shiftKey: 'Y', code: 'KeyY'},
//     {id: 13, key: 'u', width: '60px', shiftKey: 'U', code: 'KeyU'},
//     {id: 13, key: 'i', width: '60px', shiftKey: 'I', code: 'KeyI'},
//     {id: 13, key: 'o', width: '60px', shiftKey: 'O', code: 'KeyO'},
//     {id: 13, key: 'p', width: '60px', shiftKey: 'P', code: 'KeyP'},
//     {id: 13, key: '[', width: '60px', shiftKey: '{', code: 'BracketLeft'},
//     {id: 13, key: ']', width: '60px', shiftKey: '}', code: 'BracketRight'},
//     {id: 'enter-main', key: 'Enter', width: '60px', shiftKey: null, code: 'Enter'},
//     {id: 13, key: 'Caps Lock', width: '120px', shiftKey: null, code: 'CapsLock'},
//     {id: 13, key: 'a', width: '60px', shiftKey: 'A', code: 'KeyA'},
//     {id: 13, key: 's', width: '60px', shiftKey: 'S', code: 'KeyS'},
//     {id: 13, key: 'd', width: '60px', shiftKey: 'D', code: 'KeyD'},
//     {id: 13, key: 'f', width: '60px', shiftKey: 'F', code: 'KeyF'},
//     {id: 13, key: 'g', width: '60px', shiftKey: 'G', code: 'KeyG'},
//     {id: 13, key: 'h', width: '60px', shiftKey: 'H', code: 'KeyH'},
//     {id: 13, key: 'j', width: '60px', shiftKey: 'J', code: 'KeyJ'},
//     {id: 13, key: 'k', width: '60px', shiftKey: 'K', code: 'KeyK'},
//     {id: 13, key: 'l', width: '60px', shiftKey: 'L', code: 'KeyL'},
//     {id: 13, key: ';', width: '60px', shiftKey: ':', code: 'Semicolon'},
//     {id: 13, key: '\'', width: '60px', shiftKey: '\"', code: 'Quote'},
//     {id: 13, key: '\\', width: '60px', shiftKey: '|', code: 'Backslash'},
//     {id: 'enter-part', key: '', width: '30px', shiftKey: null, code: 'Enter'},
//     {id: 13, key: 'Shift', width: '92px', shiftKey: null, code: 'ShiftLeft'},
//     {id: 13, key: '`', width: '60px', shiftKey: '~', code: 'IntlBackslash'},
//     {id: 13, key: 'z', width: '60px', shiftKey: 'Z', code: 'KeyZ'},
//     {id: 13, key: 'x', width: '60px', shiftKey: 'X', code: 'KeyX'},
//     {id: 13, key: 'c', width: '60px', shiftKey: 'C', code: 'KeyC'},
//     {id: 13, key: 'v', width: '60px', shiftKey: 'V', code: 'KeyV'},
//     {id: 13, key: 'b', width: '60px', shiftKey: 'B', code: 'KeyB'},
//     {id: 13, key: 'n', width: '60px', shiftKey: 'N', code: 'KeyN'},
//     {id: 13, key: 'm', width: '60px', shiftKey: 'M', code: 'KeyM'},
//     {id: 13, key: ',', width: '60px', shiftKey: '<', code: 'Comma'},
//     {id: 13, key: '.', width: '60px', shiftKey: '>', code: 'Period'},
//     {id: 13, key: '/', width: '60px', shiftKey: '?', code: 'Slash'},
//     {id: 13, key: 'Shift ', width: '120px', shiftKey: null, code: 'ShiftRight'},
//     {id: 13, key: 'fn', width: '60px', shiftKey: null},
//     {id: 13, key: 'ctrl', width: '60px', shiftKey: null, code: 'ControlLeft'},
//     {id: 13, key: 'alt', width: '60px', shiftKey: null, code: 'AltLeft'},
//     {id: 13, key: 'cmd', width: '75px', shiftKey: null, code: 'MetaLeft'},
//     {id: 13, key: ' ', width: '308px', shiftKey: null, code: 'Space'},
//     {id: 13, key: 'cmd ', width: '75px', shiftKey: null, code: 'MetaRight'},
//     {id: 13, key: 'alt ', width: '60px', shiftKey: null, code: 'AltRight'},
//     {id: 'arrow', key: '\u02C4', width: '60px', shiftKey: null, class: 'arrow1', code: 'ArrowUp'},
//     {id: 'arrow', key: '\u003C', width: '60px', shiftKey: null, class: 'arrow2', code: 'ArrowLeft'},
//     {id: 'arrow', key: '\u02C5', width: '60px', shiftKey: null, class: 'arrow3', code: 'ArrowDown'},
//     {id: 'arrow', key: '\u003E', width: '60px', shiftKey: null, class: 'arrow4', code: 'ArrowRight'},
// ]